name: gct_mobile
description: "Prototipo rÃ¡pido de GCT Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  image_picker: ^1.2.1
  path_provider: ^2.1.2
  geolocator: ^10.1.0
  intl: ^0.19.0
  postgres: ^3.0.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true